### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [trapoom555/MiniCPM-Dense-Retriever#16]
Hi,

Niels here from the open-source team at Hugging Face. Congrats on your work! I discovered your work through the paper page: https://huggingface.co/papers/2408.00690 (feel free to claim the paper so that it appears at your HF account!).

It's great to link the 🤗 Collection to the paper, and add the paper itself to the collection.

See here on how to do that: https://huggingface.co/docs/hub/en/paper-pages#linking-a-paper-to-a-model-dataset-or-space.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by trapoom555** [comment]
Thanks for the recommendations, Niels! I've added the model cards to the paper, and authorship has been automatically credited. ✨
